runtime: nodejs14
env: standard
service: website-production
instance_class: F4
env_variables:
  NODE_ENV: 'production'
  DEPLOY_ENV: 'production'

handlers:
  - url: /_next/static
    static_dir: .next/static
    expiration: 365d

  - url: /fonts/*
    static_dir: public/fonts
    secure: always
    expiration: 10d

  - url: /static
    static_dir: public/static

  - url: /public
    static_dir: public

  - url: /papers/whitepaper
    static_files: public/papers/Celo__A_Multi_Asset_Cryptographic_Protocol_for_Decentralized_Social_Payments.pdf
    upload: public/papers/Celo__A_Multi_Asset_Cryptographic_Protocol_for_Decentralized_Social_Payments.pdf

  - url: /papers/plumo
    static_files: public/papers/proposal-plumo_celolightclient.pdf
    upload: public/papers/proposal-plumo_celolightclient.pdf

  - url: /papers/future-proof-exec
    static_files: public/papers/Future_Proof_Aid_Policy_Exec_Summary.pdf
    upload: public/papers/Future_Proof_Aid_Policy_Exec_Summary.pdf

  - url: /papers/future-proof-aid
    static_files: public/papers/Future_Proof_Aid_Policy.pdf
    upload: public/papers/Future_Proof_Aid_Policy.pdf

  - url: /papers/stability
    static_files: public/papers/Celo_Stability_Analysis.pdf
    upload: public/papers/Celo_Stability_Analysis.pdf

  - url: /papers/cbdc-velocity
    static_files: public/papers/cLabs_CBDC_Velocity_v3.pdf
    upload: public/papers/cLabs_CBDC_Velocity_v3.pdf

  - url: /papers/future-of-digital-currencies
    static_files: public/papers/shaping-future-of-digital-currencies.pdf
    upload: public/papers/shaping-future-of-digital-currencies.pdf

  - url: /.*
    script: auto
